[package]
name = "kayak_ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.8.1"
bytemuck = "1.12"
kayak_font = { git = "https://github.com/StarArawn/kayak_ui" }
morphorm = { git = "https://github.com/geom3trik/morphorm", rev = "1243152d4cebea46fd3e5098df26402c73acae91" }

[dev-dependencies]
bevy-inspector-egui = "0.12"