[package]
name = "kayak_ui"
version = "0.1.0"
edition = "2021"
resolver = "2"

[workspace]
members = ["kayak_ui_macros"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", rev="9423cb6a8d0c140e11364eb23c8feb7e576baa8c" }
bytemuck = "1.12"
dashmap = "5.4"
kayak_font = { path = "./kayak_font" }
morphorm = { git = "https://github.com/geom3trik/morphorm", rev = "1243152d4cebea46fd3e5098df26402c73acae91" }
kayak_ui_macros = { path = "./kayak_ui_macros" }
indexmap = "1.9"

[dev-dependencies]
fastrand = "1.8"

[[example]]
name = "tabs"
path = "examples/tabs/tabs.rs"
